import './globals.css';
import type { Metadata } from 'next';
import { Providers } from '@/store/Providers';
import NavBar from '../components/NavBar';
import RouteTransitionProvider from './RouteTransitionProvider';
import RouteTransition from '../components/RouteTransition';

export const metadata: Metadata = {
  title: 'ANYCOMP',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet" />
      </head>
      <body className="font-lexend antialiased">
        <Providers>
          <NavBar />
            {children}
        </Providers>
      </body>
    </html>
  );
}
